version: "2"

services:
  tor:
    image: goldy/tor-hidden-service:0.3.5.8
    links:
      - web
    environment:
      # hello and again will share the same onion v3 address
      SERVICE2_TOR_SERVICE_HOSTS: 80:web:5000
      SERVICE2_TOR_SERVICE_VERSION: '3'
      # tor v3 address private key base 64 encoded
      SERVICE2_TOR_SERVICE_KEY: |
        PT0gZWQyNTUxOXYxLXNlY3JldDogdHlwZTAgPT0AAACArobDQYyZAWXei4QZwr++
        j96H1X/gq14NwLRZ2O5DXuL0EzYKkdhZSILY85q+kfwZH8z4ceqe7u1F+0pQi/sM

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development

  redis:
    image: "redis:alpine"
