version: "3.3"

services:
    proxy:
        image: nginxproxy/nginx-proxy
        container_name: proxy
        volumes:
            - "certs:/etc/nginx/certs"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        networks: ["nginx_server"]
        restart: always
        ports:
            - 80:80
            - 443:443

    letsencrypt:
        image: nginxproxy/acme-companion
        container_name: letsencrypt
        volumes:
            - "certs:/etc/nginx/certs"
            - "vhost:/etc/nginx/vhost.d"
            - "html:/usr/share/nginx/html"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: proxy
        networks: ["nginx_server"]
        restart: always
        depends_on: ["proxy"]

networks:
  nginx_server:
    external: true

volumes:
    certs:
    vhost:
    html:
